[tool.ruff]
line-length = 100
target-version = "py311"
src = ["src"]

[tool.ruff.lint]
extend-select = ["I"]  # isort

[tool.mypy]
python_version = "3.11"
packages = ["src"]
explicit_package_bases = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
exclude = ["^\\.venv/", "^tests?/fixtures/"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
pythonpath = ["src"]
