[tool.ruff]
line-length = 100
target-version = "py310"
src = ["src"]

[tool.ruff.lint]
extend-select = ["I"]  # isort

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = false
warn_redundant_casts = true
warn_unused_ignores = true
exclude = ["^\\.venv/", "^tests?/fixtures/"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
